package main

import (
	"bufio"
	"net/http"
	"os"
	"strings"
)

// versions.yaml (generated by `make versions`) is mounted into the container
// read-only. We only need its trailing `pmm:` section here, so rather than pull
// in a YAML dependency we parse that one block by hand — the file format is
// fixed and emitted by images/versions.sh.

// PMMCatalog is the set of PMM3 server image versions selectable for a PMM node.
type PMMCatalog struct {
	Repository string   `json:"repository"`
	DefaultTag string   `json:"defaultTag"`
	Latest     string   `json:"latest"`
	Versions   []string `json:"versions"`
}

// pmmCatalogFallback is used when versions.yaml is missing or has no pmm section
// (e.g. `make versions` was never run). It still lets a PMM node deploy on the
// rolling latest tag.
var pmmCatalogFallback = PMMCatalog{
	Repository: "percona/pmm-server",
	DefaultTag: "3",
}

// versionsFilePath returns the first existing candidate path for versions.yaml.
// VERSIONS_FILE overrides; otherwise the in-container mount path is tried first,
// then repo-relative locations for local `go run` development.
func versionsFilePath() string {
	candidates := []string{
		os.Getenv("VERSIONS_FILE"),
		"/etc/dbcanvas/versions.yaml",
		"versions.yaml",
		"../versions.yaml",
	}
	for _, p := range candidates {
		if p == "" {
			continue
		}
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}
	return ""
}

// loadPMMCatalog reads and parses the `pmm:` section of versions.yaml. It never
// errors: on any problem it returns the fallback so a PMM node can still deploy.
func loadPMMCatalog() PMMCatalog {
	path := versionsFilePath()
	if path == "" {
		return pmmCatalogFallback
	}
	f, err := os.Open(path)
	if err != nil {
		return pmmCatalogFallback
	}
	defer f.Close()

	cat := PMMCatalog{}
	inPMM := false
	inVersions := false
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := sc.Text()
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		// A top-level key (no indentation) ends the pmm block.
		if !strings.HasPrefix(line, " ") {
			inPMM = trimmed == "pmm:"
			inVersions = false
			continue
		}
		if !inPMM {
			continue
		}
		// Two-space indented keys within the pmm mapping.
		if strings.HasPrefix(line, "  ") && !strings.HasPrefix(line, "    ") {
			inVersions = false
			key, val := splitYAMLKV(trimmed)
			switch key {
			case "repository":
				cat.Repository = val
			case "default_tag":
				cat.DefaultTag = val
			case "latest":
				cat.Latest = val
			case "versions":
				inVersions = true
			}
			continue
		}
		// Four-space indented list items under `versions:`.
		if inVersions && strings.HasPrefix(strings.TrimSpace(line), "- ") {
			v := unquoteYAML(strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(line), "-")))
			if v != "" {
				cat.Versions = append(cat.Versions, v)
			}
		}
	}
	if cat.Repository == "" {
		cat.Repository = pmmCatalogFallback.Repository
	}
	if cat.DefaultTag == "" {
		cat.DefaultTag = pmmCatalogFallback.DefaultTag
	}
	return cat
}

// splitYAMLKV splits "key: value" and unquotes the value.
func splitYAMLKV(s string) (string, string) {
	i := strings.Index(s, ":")
	if i < 0 {
		return s, ""
	}
	return strings.TrimSpace(s[:i]), unquoteYAML(strings.TrimSpace(s[i+1:]))
}

func unquoteYAML(s string) string {
	if len(s) >= 2 && (s[0] == '"' || s[0] == '\'') && s[len(s)-1] == s[0] {
		return s[1 : len(s)-1]
	}
	return s
}

// validPMMTag reports whether tag is one this catalog allows: the rolling
// default tag, "latest", or one of the discovered minor versions. Guards against
// arbitrary user-supplied image tags reaching the Docker pull.
func (c PMMCatalog) validPMMTag(tag string) bool {
	if tag == "" || tag == c.DefaultTag || tag == "latest" {
		return true
	}
	for _, v := range c.Versions {
		if v == tag {
			return true
		}
	}
	return false
}

func (a *App) handlePMMCatalog(w http.ResponseWriter, r *http.Request) {
	if _, ok := a.currentUser(r); !ok {
		writeErr(w, http.StatusUnauthorized, "authentication required")
		return
	}
	writeJSON(w, http.StatusOK, loadPMMCatalog())
}
