package main

import (
	"bufio"
	"net/http"
	"os"
	"strings"
)

// versions.yaml (generated by `make versions`) is mounted into the container
// read-only. We only need its trailing `pmm:` section here, so rather than pull
// in a YAML dependency we parse that one block by hand — the file format is
// fixed and emitted by images/versions.sh.

// PMMCatalog is the set of PMM3 server image versions selectable for a PMM node.
type PMMCatalog struct {
	Repository string   `json:"repository"`
	DefaultTag string   `json:"defaultTag"`
	Latest     string   `json:"latest"`
	Versions   []string `json:"versions"`
}

// pmmCatalogFallback is used when versions.yaml is missing or has no pmm section
// (e.g. `make versions` was never run). It still lets a PMM node deploy on the
// rolling latest tag.
var pmmCatalogFallback = PMMCatalog{
	Repository: "percona/pmm-server",
	DefaultTag: "3",
}

// versionsFilePath returns the first existing candidate path for versions.yaml.
// VERSIONS_FILE overrides; otherwise the in-container mount path is tried first,
// then repo-relative locations for local `go run` development.
func versionsFilePath() string {
	candidates := []string{
		os.Getenv("VERSIONS_FILE"),
		"/etc/dbcanvas/versions.yaml",
		"versions.yaml",
		"../versions.yaml",
	}
	for _, p := range candidates {
		if p == "" {
			continue
		}
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}
	return ""
}

// loadPMMCatalog reads and parses the `pmm:` section of versions.yaml. It never
// errors: on any problem it returns the fallback so a PMM node can still deploy.
func loadPMMCatalog() PMMCatalog {
	path := versionsFilePath()
	if path == "" {
		return pmmCatalogFallback
	}
	f, err := os.Open(path)
	if err != nil {
		return pmmCatalogFallback
	}
	defer f.Close()

	cat := PMMCatalog{}
	inPMM := false
	inVersions := false
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := sc.Text()
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		// A top-level key (no indentation) ends the pmm block.
		if !strings.HasPrefix(line, " ") {
			inPMM = trimmed == "pmm:"
			inVersions = false
			continue
		}
		if !inPMM {
			continue
		}
		// Two-space indented keys within the pmm mapping.
		if strings.HasPrefix(line, "  ") && !strings.HasPrefix(line, "    ") {
			inVersions = false
			key, val := splitYAMLKV(trimmed)
			switch key {
			case "repository":
				cat.Repository = val
			case "default_tag":
				cat.DefaultTag = val
			case "latest":
				cat.Latest = val
			case "versions":
				inVersions = true
			}
			continue
		}
		// Four-space indented list items under `versions:`.
		if inVersions && strings.HasPrefix(strings.TrimSpace(line), "- ") {
			v := unquoteYAML(strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(line), "-")))
			if v != "" {
				cat.Versions = append(cat.Versions, v)
			}
		}
	}
	if cat.Repository == "" {
		cat.Repository = pmmCatalogFallback.Repository
	}
	if cat.DefaultTag == "" {
		cat.DefaultTag = pmmCatalogFallback.DefaultTag
	}
	return cat
}

// splitYAMLKV splits "key: value" and unquotes the value.
func splitYAMLKV(s string) (string, string) {
	i := strings.Index(s, ":")
	if i < 0 {
		return s, ""
	}
	return strings.TrimSpace(s[:i]), unquoteYAML(strings.TrimSpace(s[i+1:]))
}

func unquoteYAML(s string) string {
	if len(s) >= 2 && (s[0] == '"' || s[0] == '\'') && s[len(s)-1] == s[0] {
		return s[1 : len(s)-1]
	}
	return s
}

// validPMMTag reports whether tag is one this catalog allows: the rolling
// default tag, "latest", or one of the discovered minor versions. Guards against
// arbitrary user-supplied image tags reaching the Docker pull.
func (c PMMCatalog) validPMMTag(tag string) bool {
	if tag == "" || tag == c.DefaultTag || tag == "latest" {
		return true
	}
	for _, v := range c.Versions {
		if v == tag {
			return true
		}
	}
	return false
}

func (a *App) handlePMMCatalog(w http.ResponseWriter, r *http.Request) {
	if _, ok := a.currentUser(r); !ok {
		writeErr(w, http.StatusUnauthorized, "authentication required")
		return
	}
	writeJSON(w, http.StatusOK, loadPMMCatalog())
}

// PXCImage is one built image's installable Percona XtraDB Cluster versions,
// keyed by major series — drives the PXC frame's OS/version pickers.
type PXCImage struct {
	OS        string              `json:"os"`
	OSVersion string              `json:"osVersion"`
	Arch      string              `json:"arch"`
	Platform  string              `json:"platform"`
	Versions  map[string][]string `json:"versions"` // "8.0" → [...], "8.4" → [...]
}

// loadPXCCatalog / loadProxySQLCatalog / loadPSCatalog / loadPSMDBCatalog parse the
// per-image `percona_xtradb_cluster` / `proxysql` / `percona_server` /
// `percona_server_mongodb` sections of versions.yaml.
func loadPXCCatalog() []PXCImage      { return loadImageCatalog("percona_xtradb_cluster") }
func loadProxySQLCatalog() []PXCImage { return loadImageCatalog("proxysql") }
func loadPSCatalog() []PXCImage       { return loadImageCatalog("percona_server") }
func loadPSMDBCatalog() []PXCImage    { return loadImageCatalog("percona_server_mongodb") }
func loadPPGCatalog() []PXCImage      { return loadImageCatalog("percona_postgresql") }

// loadImagesCatalog returns every built image with its os/version/arch/platform
// but without any version map — used by nodes that only need the OS matrix
// (e.g. HAProxy), where the per-product catalogs would drop images that have an
// empty version map for that product.
func loadImagesCatalog() []PXCImage { return loadImageCatalog("") }

// loadImageCatalog parses the per-image `<wantSection>` major-series map of
// versions.yaml (each image's installable versions keyed by series). It mirrors
// the YAML the generator emits. Never errors — returns nil on any problem.
func loadImageCatalog(wantSection string) []PXCImage {
	path := versionsFilePath()
	if path == "" {
		return nil
	}
	f, err := os.Open(path)
	if err != nil {
		return nil
	}
	defer f.Close()

	var out []PXCImage
	var cur *PXCImage
	inImages := false
	inWanted := false // inside the requested per-image section
	series := ""      // current major series key while reading its list

	flush := func() {
		if cur != nil {
			out = append(out, *cur)
			cur = nil
		}
	}

	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := sc.Text()
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		// Top-level key (no indent) — ends any image and the images block.
		if !strings.HasPrefix(line, " ") {
			flush()
			inImages = strings.HasPrefix(line, "images:")
			inWanted, series = false, ""
			continue
		}
		if !inImages {
			continue
		}
		// New image entry.
		if strings.HasPrefix(line, "  - os:") {
			flush()
			cur = &PXCImage{Versions: map[string][]string{}}
			cur.OS = unquoteYAML(strings.TrimSpace(strings.TrimPrefix(line, "  - os:")))
			inWanted, series = false, ""
			continue
		}
		if cur == nil {
			continue
		}
		// 4-space entry key / section header.
		if strings.HasPrefix(line, "    ") && !strings.HasPrefix(line, "      ") {
			inWanted, series = false, ""
			key, val := splitYAMLKV(trimmed)
			switch key {
			case "version":
				cur.OSVersion = val
			case "arch":
				cur.Arch = val
			case "platform":
				cur.Platform = val
			case wantSection:
				inWanted = true
			}
			continue
		}
		// 6-space major-series key under a section.
		if strings.HasPrefix(line, "      ") && !strings.HasPrefix(line, "        ") {
			if !inWanted {
				series = ""
				continue
			}
			key, val := splitYAMLKV(trimmed)
			series = unquoteYAML(key) // keys like "8.0" / "2" are quoted in the YAML
			if val == "[]" {
				cur.Versions[series] = []string{}
				series = ""
			} else if _, ok := cur.Versions[series]; !ok {
				cur.Versions[series] = []string{}
			}
			continue
		}
		// 8-space list item under the current series.
		if strings.HasPrefix(line, "        - ") {
			if inWanted && series != "" {
				v := unquoteYAML(strings.TrimSpace(strings.TrimPrefix(trimmed, "-")))
				if v != "" {
					cur.Versions[series] = append(cur.Versions[series], v)
				}
			}
		}
	}
	flush()
	return out
}

func (a *App) handlePXCCatalog(w http.ResponseWriter, r *http.Request) {
	if _, ok := a.currentUser(r); !ok {
		writeErr(w, http.StatusUnauthorized, "authentication required")
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"images": loadPXCCatalog()})
}

func (a *App) handleProxySQLCatalog(w http.ResponseWriter, r *http.Request) {
	if _, ok := a.currentUser(r); !ok {
		writeErr(w, http.StatusUnauthorized, "authentication required")
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"images": loadProxySQLCatalog()})
}

func (a *App) handlePSCatalog(w http.ResponseWriter, r *http.Request) {
	if _, ok := a.currentUser(r); !ok {
		writeErr(w, http.StatusUnauthorized, "authentication required")
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"images": loadPSCatalog()})
}

func (a *App) handlePSMDBCatalog(w http.ResponseWriter, r *http.Request) {
	if _, ok := a.currentUser(r); !ok {
		writeErr(w, http.StatusUnauthorized, "authentication required")
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"images": loadPSMDBCatalog()})
}

func (a *App) handlePPGCatalog(w http.ResponseWriter, r *http.Request) {
	if _, ok := a.currentUser(r); !ok {
		writeErr(w, http.StatusUnauthorized, "authentication required")
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"images": loadPPGCatalog()})
}

func (a *App) handleImagesCatalog(w http.ResponseWriter, r *http.Request) {
	if _, ok := a.currentUser(r); !ok {
		writeErr(w, http.StatusUnauthorized, "authentication required")
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"images": loadImagesCatalog()})
}

// loadPDPSCatalog reads the top-level `pdps:` list of percona-release repositories
// from versions.yaml. Never errors — returns nil on any problem.
func loadPDPSCatalog() []string {
	path := versionsFilePath()
	if path == "" {
		return nil
	}
	f, err := os.Open(path)
	if err != nil {
		return nil
	}
	defer f.Close()

	var out []string
	inPDPS := false
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := sc.Text()
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		if !strings.HasPrefix(line, " ") {
			inPDPS = trimmed == "pdps:" || trimmed == "pdps: []"
			if trimmed == "pdps: []" {
				inPDPS = false
			}
			continue
		}
		if inPDPS && strings.HasPrefix(trimmed, "- ") {
			v := unquoteYAML(strings.TrimSpace(strings.TrimPrefix(trimmed, "-")))
			if v != "" {
				out = append(out, v)
			}
		}
	}
	return out
}

func (a *App) handlePDPSCatalog(w http.ResponseWriter, r *http.Request) {
	if _, ok := a.currentUser(r); !ok {
		writeErr(w, http.StatusUnauthorized, "authentication required")
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"repos": loadPDPSCatalog()})
}
