package main

import (
	"bufio"
	"net/http"
	"os"
	"strings"
)

// versions.yaml (generated by `make versions`) is mounted into the container
// read-only. We only need its trailing `pmm:` section here, so rather than pull
// in a YAML dependency we parse that one block by hand — the file format is
// fixed and emitted by images/versions.sh.

// PMMCatalog is the set of PMM3 server image versions selectable for a PMM node.
type PMMCatalog struct {
	Repository string   `json:"repository"`
	DefaultTag string   `json:"defaultTag"`
	Latest     string   `json:"latest"`
	Versions   []string `json:"versions"`
}

// pmmCatalogFallback is used when versions.yaml is missing or has no pmm section
// (e.g. `make versions` was never run). It still lets a PMM node deploy on the
// rolling latest tag.
var pmmCatalogFallback = PMMCatalog{
	Repository: "percona/pmm-server",
	DefaultTag: "3",
}

// k3sCatalogFallback is used when versions.yaml has no k3s section (`make versions` was never run).
// The pinned tag is one every Percona operator installs on: k3d's own default (v1.31.x) is too old
// for the ps-operator's CRDs, whose CEL rules need the API server's `format` library.
var k3sCatalogFallback = PMMCatalog{
	Repository: "rancher/k3s",
	Latest:     "v1.33.13-k3s1",
}

// versionsFilePath returns the first existing candidate path for versions.yaml.
// VERSIONS_FILE overrides; otherwise the in-container mount path is tried first,
// then repo-relative locations for local `go run` development.
func versionsFilePath() string {
	candidates := []string{
		os.Getenv("VERSIONS_FILE"),
		"/etc/dbcanvas/versions.yaml",
		"versions.yaml",
		"../versions.yaml",
	}
	for _, p := range candidates {
		if p == "" {
			continue
		}
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}
	return ""
}

// loadPMMCatalog reads and parses the `pmm:` section of versions.yaml. It never
// errors: on any problem it returns the fallback so a PMM node can still deploy.
func loadPMMCatalog() PMMCatalog { return loadTagCatalog("pmm:", pmmCatalogFallback) }

// loadK3SCatalog reads the `k3s:` section — the Kubernetes versions a K3D cluster frame can run.
// k3d creates its nodes from rancher/k3s:<tag>, so the tag *is* the Kubernetes version.
func loadK3SCatalog() PMMCatalog { return loadTagCatalog("k3s:", k3sCatalogFallback) }

// loadTagCatalog parses one of versions.yaml's two-level tag sections (`pmm:`, `k3s:`): a
// repository, a latest, and a list of versions. It never fails — a missing or unreadable file
// yields the fallback, so a node can still deploy on a sane default.
func loadTagCatalog(section string, fallback PMMCatalog) PMMCatalog {
	path := versionsFilePath()
	if path == "" {
		return fallback
	}
	f, err := os.Open(path)
	if err != nil {
		return fallback
	}
	defer f.Close()

	cat := PMMCatalog{}
	inPMM := false
	inVersions := false
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := sc.Text()
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		// A top-level key (no indentation) ends the section.
		if !strings.HasPrefix(line, " ") {
			inPMM = trimmed == section
			inVersions = false
			continue
		}
		if !inPMM {
			continue
		}
		// Two-space indented keys within the pmm mapping.
		if strings.HasPrefix(line, "  ") && !strings.HasPrefix(line, "    ") {
			inVersions = false
			key, val := splitYAMLKV(trimmed)
			switch key {
			case "repository":
				cat.Repository = val
			case "default_tag":
				cat.DefaultTag = val
			case "latest":
				cat.Latest = val
			case "versions":
				inVersions = true
			}
			continue
		}
		// Four-space indented list items under `versions:`.
		if inVersions && strings.HasPrefix(strings.TrimSpace(line), "- ") {
			v := unquoteYAML(strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(line), "-")))
			if v != "" {
				cat.Versions = append(cat.Versions, v)
			}
		}
	}
	if cat.Repository == "" {
		cat.Repository = fallback.Repository
	}
	if cat.DefaultTag == "" {
		cat.DefaultTag = fallback.DefaultTag
	}
	if cat.Latest == "" {
		cat.Latest = fallback.Latest
	}
	return cat
}

// resolveK3SVersion returns the k3s image tag a K3D frame should run: the requested one when the
// catalog knows it, or the catalog's latest when the frame asked for "latest" (the default).
// ok=false means an unknown tag, which would otherwise reach an image pull that cannot succeed.
func (c PMMCatalog) resolveK3SVersion(want string) (string, bool) {
	want = strings.TrimSpace(want)
	if want == "" || want == "latest" {
		return c.Latest, c.Latest != ""
	}
	for _, v := range c.Versions {
		if v == want {
			return v, true
		}
	}
	return "", false
}

// k3sImageRef is the image k3d creates a cluster's nodes from.
func (c PMMCatalog) k3sImageRef(tag string) string {
	repo := c.Repository
	if repo == "" {
		repo = k3sCatalogFallback.Repository
	}
	return repo + ":" + tag
}

// splitYAMLKV splits "key: value" and unquotes the value.
func splitYAMLKV(s string) (string, string) {
	i := strings.Index(s, ":")
	if i < 0 {
		return s, ""
	}
	return strings.TrimSpace(s[:i]), unquoteYAML(strings.TrimSpace(s[i+1:]))
}

func unquoteYAML(s string) string {
	if len(s) >= 2 && (s[0] == '"' || s[0] == '\'') && s[len(s)-1] == s[0] {
		return s[1 : len(s)-1]
	}
	return s
}

// validPMMTag reports whether tag is one this catalog allows: the rolling
// default tag, "latest", or one of the discovered minor versions. Guards against
// arbitrary user-supplied image tags reaching the Docker pull.
func (c PMMCatalog) validPMMTag(tag string) bool {
	if tag == "" || tag == c.DefaultTag || tag == "latest" {
		return true
	}
	for _, v := range c.Versions {
		if v == tag {
			return true
		}
	}
	return false
}

func (a *App) handlePMMCatalog(w http.ResponseWriter, r *http.Request) {
	if _, ok := a.currentUser(r); !ok {
		writeErr(w, http.StatusUnauthorized, "authentication required")
		return
	}
	writeJSON(w, http.StatusOK, loadPMMCatalog())
}

// OperatorVersions is one Percona Kubernetes operator's available releases. A K3D node
// installs an operator from its matching git tag (deploy/bundle.yaml + deploy/cr.yaml), so a
// version here is both an image tag and a source tag.
type OperatorVersions struct {
	Repository string   `json:"repository"`
	Latest     string   `json:"latest"`
	Versions   []string `json:"versions"`
}

// OperatorCatalog maps a product ("pxc" | "psmdb" | "pg") to its releases.
type OperatorCatalog map[string]OperatorVersions

// loadOperatorCatalog reads the `operators:` section of versions.yaml. Like the pmm parser it
// never errors — an empty catalog just means the K3D frame offers no operator versions (run
// `make versions`), which validation reports rather than failing at deploy.
func loadOperatorCatalog() OperatorCatalog {
	cat := OperatorCatalog{}
	path := versionsFilePath()
	if path == "" {
		return cat
	}
	f, err := os.Open(path)
	if err != nil {
		return cat
	}
	defer f.Close()

	inOperators := false // inside the top-level `operators:` block
	product := ""        // the 2-space key currently being filled (pxc | psmdb | pg)
	inVersions := false  // inside that product's `versions:` list
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := sc.Text()
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		// A top-level key ends the operators block.
		if !strings.HasPrefix(line, " ") {
			inOperators = trimmed == "operators:"
			product, inVersions = "", false
			continue
		}
		if !inOperators {
			continue
		}
		// Two-space key: a product ("pxc:").
		if strings.HasPrefix(line, "  ") && !strings.HasPrefix(line, "    ") {
			product = strings.TrimSuffix(trimmed, ":")
			inVersions = false
			if product != "" {
				cat[product] = OperatorVersions{}
			}
			continue
		}
		if product == "" {
			continue
		}
		// Four-space keys: the product's fields.
		if strings.HasPrefix(line, "    ") && !strings.HasPrefix(line, "      ") {
			inVersions = false
			key, val := splitYAMLKV(trimmed)
			ov := cat[product]
			switch key {
			case "repository":
				ov.Repository = val
			case "latest":
				ov.Latest = val
			case "versions":
				inVersions = true
			}
			cat[product] = ov
			continue
		}
		// Six-space list items under `versions:`.
		if inVersions && strings.HasPrefix(trimmed, "- ") {
			if v := unquoteYAML(strings.TrimSpace(strings.TrimPrefix(trimmed, "-"))); v != "" {
				ov := cat[product]
				ov.Versions = append(ov.Versions, v)
				cat[product] = ov
			}
		}
	}
	return cat
}

// resolveOperatorVersion returns the version to install for a product: the requested one when the
// catalog knows it, or the catalog's latest when none was requested. ok=false means the request
// cannot be honoured — an unknown tag (which would otherwise reach a git/image fetch), or an empty
// catalog with no latest to fall back on.
func (c OperatorCatalog) resolveOperatorVersion(product, want string) (string, bool) {
	ov, known := c[product]
	if !known {
		return "", false
	}
	if want == "" {
		return ov.Latest, ov.Latest != ""
	}
	for _, v := range ov.Versions {
		if v == want {
			return v, true
		}
	}
	return "", false
}

func (a *App) handleOperatorsCatalog(w http.ResponseWriter, r *http.Request) {
	if _, ok := a.currentUser(r); !ok {
		writeErr(w, http.StatusUnauthorized, "authentication required")
		return
	}
	writeJSON(w, http.StatusOK, loadOperatorCatalog())
}

func (a *App) handleK3SCatalog(w http.ResponseWriter, r *http.Request) {
	if _, ok := a.currentUser(r); !ok {
		writeErr(w, http.StatusUnauthorized, "authentication required")
		return
	}
	writeJSON(w, http.StatusOK, loadK3SCatalog())
}

// PXCImage is one built image's installable Percona XtraDB Cluster versions,
// keyed by major series — drives the PXC frame's OS/version pickers.
type PXCImage struct {
	OS        string              `json:"os"`
	OSVersion string              `json:"osVersion"`
	Arch      string              `json:"arch"`
	Platform  string              `json:"platform"`
	Versions  map[string][]string `json:"versions"` // "8.0" → [...], "8.4" → [...]
}

// loadPXCCatalog / loadProxySQLCatalog / loadPSCatalog / loadPSMDBCatalog parse the
// per-image `percona_xtradb_cluster` / `proxysql` / `percona_server` /
// `percona_server_mongodb` sections of versions.yaml.
func loadPXCCatalog() []PXCImage      { return loadImageCatalog("percona_xtradb_cluster") }
func loadProxySQLCatalog() []PXCImage { return loadImageCatalog("proxysql") }
func loadPSCatalog() []PXCImage       { return loadImageCatalog("percona_server") }
func loadPSMDBCatalog() []PXCImage    { return loadImageCatalog("percona_server_mongodb") }
func loadPPGCatalog() []PXCImage      { return loadImageCatalog("percona_postgresql") }

// loadSpockCatalog returns the Spock (source-built PostgreSQL) availability:
// which PG majors/minors and OS/platforms Spock can be deployed on. Unlike the
// PPG catalog (Percona packages), this comes from the `spock:` section that
// `make versions` derives from the Spock patch set + postgresql.org release tags,
// and is populated only for Oracle Linux images (Spock compiles on RHEL only).
func loadSpockCatalog() []PXCImage { return loadImageCatalog("spock") }

// loadImagesCatalog returns every built image with its os/version/arch/platform
// but without any version map — used by nodes that only need the OS matrix
// (e.g. HAProxy), where the per-product catalogs would drop images that have an
// empty version map for that product.
func loadImagesCatalog() []PXCImage { return loadImageCatalog("") }

// loadImageCatalog parses the per-image `<wantSection>` major-series map of
// versions.yaml (each image's installable versions keyed by series). It mirrors
// the YAML the generator emits. Never errors — returns nil on any problem.
func loadImageCatalog(wantSection string) []PXCImage {
	path := versionsFilePath()
	if path == "" {
		return nil
	}
	f, err := os.Open(path)
	if err != nil {
		return nil
	}
	defer f.Close()

	var out []PXCImage
	var cur *PXCImage
	inImages := false
	inWanted := false // inside the requested per-image section
	series := ""      // current major series key while reading its list

	flush := func() {
		if cur != nil {
			out = append(out, *cur)
			cur = nil
		}
	}

	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := sc.Text()
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		// Top-level key (no indent) — ends any image and the images block.
		if !strings.HasPrefix(line, " ") {
			flush()
			inImages = strings.HasPrefix(line, "images:")
			inWanted, series = false, ""
			continue
		}
		if !inImages {
			continue
		}
		// New image entry.
		if strings.HasPrefix(line, "  - os:") {
			flush()
			cur = &PXCImage{Versions: map[string][]string{}}
			cur.OS = unquoteYAML(strings.TrimSpace(strings.TrimPrefix(line, "  - os:")))
			inWanted, series = false, ""
			continue
		}
		if cur == nil {
			continue
		}
		// 4-space entry key / section header.
		if strings.HasPrefix(line, "    ") && !strings.HasPrefix(line, "      ") {
			inWanted, series = false, ""
			key, val := splitYAMLKV(trimmed)
			switch key {
			case "version":
				cur.OSVersion = val
			case "arch":
				cur.Arch = val
			case "platform":
				cur.Platform = val
			case wantSection:
				inWanted = true
			}
			continue
		}
		// 6-space major-series key under a section.
		if strings.HasPrefix(line, "      ") && !strings.HasPrefix(line, "        ") {
			if !inWanted {
				series = ""
				continue
			}
			key, val := splitYAMLKV(trimmed)
			series = unquoteYAML(key) // keys like "8.0" / "2" are quoted in the YAML
			if val == "[]" {
				cur.Versions[series] = []string{}
				series = ""
			} else if _, ok := cur.Versions[series]; !ok {
				cur.Versions[series] = []string{}
			}
			continue
		}
		// 8-space list item under the current series.
		if strings.HasPrefix(line, "        - ") {
			if inWanted && series != "" {
				v := unquoteYAML(strings.TrimSpace(strings.TrimPrefix(trimmed, "-")))
				if v != "" {
					cur.Versions[series] = append(cur.Versions[series], v)
				}
			}
		}
	}
	flush()
	return out
}

func (a *App) handlePXCCatalog(w http.ResponseWriter, r *http.Request) {
	if _, ok := a.currentUser(r); !ok {
		writeErr(w, http.StatusUnauthorized, "authentication required")
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"images": loadPXCCatalog()})
}

func (a *App) handleProxySQLCatalog(w http.ResponseWriter, r *http.Request) {
	if _, ok := a.currentUser(r); !ok {
		writeErr(w, http.StatusUnauthorized, "authentication required")
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"images": loadProxySQLCatalog()})
}

func (a *App) handlePSCatalog(w http.ResponseWriter, r *http.Request) {
	if _, ok := a.currentUser(r); !ok {
		writeErr(w, http.StatusUnauthorized, "authentication required")
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"images": loadPSCatalog()})
}

func (a *App) handlePSMDBCatalog(w http.ResponseWriter, r *http.Request) {
	if _, ok := a.currentUser(r); !ok {
		writeErr(w, http.StatusUnauthorized, "authentication required")
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"images": loadPSMDBCatalog()})
}

func (a *App) handlePPGCatalog(w http.ResponseWriter, r *http.Request) {
	if _, ok := a.currentUser(r); !ok {
		writeErr(w, http.StatusUnauthorized, "authentication required")
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"images": loadPPGCatalog()})
}

func (a *App) handleSpockCatalog(w http.ResponseWriter, r *http.Request) {
	if _, ok := a.currentUser(r); !ok {
		writeErr(w, http.StatusUnauthorized, "authentication required")
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"images": loadSpockCatalog()})
}

func (a *App) handleImagesCatalog(w http.ResponseWriter, r *http.Request) {
	if _, ok := a.currentUser(r); !ok {
		writeErr(w, http.StatusUnauthorized, "authentication required")
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"images": loadImagesCatalog()})
}

// loadPDPSCatalog reads the top-level `pdps:` list of percona-release repositories
// from versions.yaml. Never errors — returns nil on any problem.
func loadPDPSCatalog() []string {
	path := versionsFilePath()
	if path == "" {
		return nil
	}
	f, err := os.Open(path)
	if err != nil {
		return nil
	}
	defer f.Close()

	var out []string
	inPDPS := false
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := sc.Text()
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		if !strings.HasPrefix(line, " ") {
			inPDPS = trimmed == "pdps:" || trimmed == "pdps: []"
			if trimmed == "pdps: []" {
				inPDPS = false
			}
			continue
		}
		if inPDPS && strings.HasPrefix(trimmed, "- ") {
			v := unquoteYAML(strings.TrimSpace(strings.TrimPrefix(trimmed, "-")))
			if v != "" {
				out = append(out, v)
			}
		}
	}
	return out
}

func (a *App) handlePDPSCatalog(w http.ResponseWriter, r *http.Request) {
	if _, ok := a.currentUser(r); !ok {
		writeErr(w, http.StatusUnauthorized, "authentication required")
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"repos": loadPDPSCatalog()})
}
