#!/usr/bin/env bash
#
# Build systemd-enabled base images for selectable container instances.
#
# Matrix: {oraclelinux:8, oraclelinux:9, oraclelinux:10, ubuntu:22.04,
#          ubuntu:24.04} × {linux/amd64, linux/arm64}.
#
# Each image installs systemd (PID 1) plus net-tools, the OpenLDAP client,
# sysstat, percona-release and percona-toolkit (see images/*.Dockerfile).
#
# Successful builds are recorded in versions.yaml at the repo root; that file
# drives an OS/version picker for creating container instances later. A build
# may fail (e.g. the local Docker cannot emulate a non-native platform) — that
# is expected and tolerated: failures are logged and skipped, never recorded.

set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGES_DIR="$ROOT/images"
OUT="$ROOT/versions.yaml"
IMAGE_PREFIX="dbcanvas-systemd"

# entry format: base_image|os|version|dockerfile
MATRIX=(
  "oraclelinux:8|oraclelinux|8|rhel.Dockerfile"
  "oraclelinux:9|oraclelinux|9|rhel.Dockerfile"
  "oraclelinux:10|oraclelinux|10|rhel.Dockerfile"
  "ubuntu:22.04|ubuntu|22.04|debian.Dockerfile"
  "ubuntu:24.04|ubuntu|24.04|debian.Dockerfile"
)
PLATFORMS=("linux/amd64" "linux/arm64")

ts() { date -u +"%Y-%m-%dT%H:%M:%SZ"; }

declare -a SUCCESS=()
declare -a FAILED=()

for entry in "${MATRIX[@]}"; do
  IFS='|' read -r base os version dockerfile <<<"$entry"
  for platform in "${PLATFORMS[@]}"; do
    arch="${platform#linux/}"
    tag="${IMAGE_PREFIX}:${os}-${version}-${arch}"
    echo "=================================================================="
    echo "==> building ${tag}  (base=${base}, platform=${platform})"
    echo "=================================================================="
    if docker build \
        --platform "$platform" \
        --build-arg "BASE_IMAGE=${base}" \
        -f "$IMAGES_DIR/$dockerfile" \
        -t "$tag" \
        "$IMAGES_DIR"; then
      echo "    OK    ${tag}"
      SUCCESS+=("${os}|${version}|${platform}|${arch}|${tag}|${base}|$(ts)")
    else
      echo "    FAIL  ${tag}  (skipped)"
      FAILED+=("${tag} (${platform})")
    fi
  done
done

# ---- write versions.yaml ----
{
  echo "# Generated by \`make images\`. Do not edit by hand — regenerate instead."
  echo "# Successful systemd base-image builds, selectable as container instances"
  echo "# (OS + version picker). Re-run: make images"
  echo "generated_at: $(ts)"
  echo "image_prefix: ${IMAGE_PREFIX}"
  if [ "${#SUCCESS[@]}" -eq 0 ]; then
    echo "images: []"
  else
    echo "images:"
    for s in "${SUCCESS[@]}"; do
      IFS='|' read -r os version platform arch tag base built <<<"$s"
      echo "  - os: ${os}"
      echo "    version: \"${version}\""
      echo "    platform: ${platform}"
      echo "    arch: ${arch}"
      echo "    tag: ${tag}"
      echo "    base: ${base}"
      echo "    built_at: ${built}"
    done
  fi
} >"$OUT"

echo ""
echo "=================================================================="
echo "Recorded ${#SUCCESS[@]} successful build(s) → ${OUT}"
if [ "${#FAILED[@]}" -gt 0 ]; then
  echo "Skipped ${#FAILED[@]} failed build(s):"
  for f in "${FAILED[@]}"; do echo "  - ${f}"; done
fi
echo "=================================================================="
