package dev.dbcanvas.ledgersim.db;

import dev.dbcanvas.ledgersim.conn.Engine;

import java.sql.SQLException;

/**
 * The handful of places where one schema and one workload cannot be written
 * once. Kept to a list this short on purpose: the simulator is supposed to put
 * the *same* transactions through two engines, and every extra dialect branch is
 * a place where "MySQL is slower than PostgreSQL here" stops being a fair claim.
 */
public final class Dialect {
    public final Engine engine;

    public Dialect(Engine engine) { this.engine = engine; }

    public boolean isMySQL() { return engine == Engine.MYSQL; }

    /** Auto-assigned primary key column. */
    public String identityPk() {
        return isMySQL()
                ? "BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY"
                : "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
    }

    public String timestampType() {
        return isMySQL() ? "DATETIME(3)" : "TIMESTAMPTZ";
    }

    public String nowExpr() {
        return isMySQL() ? "CURRENT_TIMESTAMP(3)" : "CURRENT_TIMESTAMP";
    }

    /** InnoDB is explicit so a server with a different default engine still gets row locks. */
    public String tableSuffix() {
        return isMySQL() ? " ENGINE=InnoDB DEFAULT CHARSET=utf8mb4" : "";
    }

    /** The statement that limits how long a row lock is waited for, or null. */
    public String lockWaitStatement(int seconds) {
        return isMySQL()
                ? "SET SESSION innodb_lock_wait_timeout = " + seconds
                : "SET LOCAL lock_timeout = '" + seconds + "s'";
    }

    /**
     * Whether a failure is the engine having chosen this transaction as a
     * deadlock victim — the one error class a correct application is expected to
     * retry rather than report.
     */
    public static boolean isDeadlock(SQLException e) {
        String s = e.getSQLState();
        if ("40001".equals(s) || "40P01".equals(s)) return true;   // serialization failure / deadlock
        return e.getErrorCode() == 1213;                            // MySQL ER_LOCK_DEADLOCK
    }

    /** A lock wait that ran out of patience: retryable, but not the same event. */
    public static boolean isLockTimeout(SQLException e) {
        String s = e.getSQLState();
        if ("55P03".equals(s)) return true;                         // PG lock_not_available
        return e.getErrorCode() == 1205;                            // MySQL ER_LOCK_WAIT_TIMEOUT
    }
}
