package dev.dbcanvas.ledgersim.db;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

/**
 * The ledger schema: accounts, orders and their lines, and the double-entry
 * postings that tie them together.
 *
 * <p>It is a genuine double entry — every posting writes a matched debit and
 * credit, so {@code SUM(amount_minor)} over ledger_entries is zero at rest, and
 * any transaction that half-committed would show up as a non-zero total. That
 * makes correctness observable, which is what lets the isolation-level knob be
 * more than a setting: drop to READ UNCOMMITTED or lose a rollback and the
 * dashboard's balance check stops adding up.
 *
 * <p>Money is stored in minor units as BIGINT. Never a float, and not DECIMAL
 * either — the arithmetic here is exact addition, and integer columns keep the
 * two engines comparing like for like.
 */
public final class Schema {
    private static final Logger log = LoggerFactory.getLogger(Schema.class);

    /**
     * Revenue accounts occupy ids 1..REVENUE_SHARDS and customers start at
     * FIRST_CUSTOMER_ID. Every order credits a revenue account, so that row is the
     * hot one — and how many of these shards the workload spreads across is the
     * single most effective contention knob in the simulator. One shard serialises
     * every transaction in the system on one row; eight makes the contention
     * visible without dominating. See Knobs.revenueShards.
     *
     * <p>Accounts are always inserted with explicit ids (the seeder assigns them),
     * which is why PostgreSQL's identity column is GENERATED BY DEFAULT and not
     * ALWAYS. Nothing auto-generates an account id, so the sequence never has to
     * catch up.
     */
    public static final int REVENUE_SHARDS = 8;
    public static final long FIRST_CUSTOMER_ID = 100;

    private Schema() {}

    public static List<String> ddl(Dialect d) {
        List<String> out = new ArrayList<>();
        out.add("""
                CREATE TABLE IF NOT EXISTS accounts (
                  id %s,
                  name VARCHAR(80) NOT NULL,
                  currency CHAR(3) NOT NULL,
                  balance_minor BIGINT NOT NULL,
                  version BIGINT NOT NULL,
                  updated_at %s NOT NULL
                )%s""".formatted(d.identityPk(), d.timestampType(), d.tableSuffix()));
        out.add("""
                CREATE TABLE IF NOT EXISTS orders (
                  id %s,
                  account_id BIGINT NOT NULL,
                  status VARCHAR(16) NOT NULL,
                  total_minor BIGINT NOT NULL,
                  created_at %s NOT NULL,
                  updated_at %s NOT NULL
                )%s""".formatted(d.identityPk(), d.timestampType(), d.timestampType(), d.tableSuffix()));
        out.add("""
                CREATE TABLE IF NOT EXISTS order_lines (
                  id %s,
                  order_id BIGINT NOT NULL,
                  sku VARCHAR(32) NOT NULL,
                  qty INT NOT NULL,
                  unit_minor BIGINT NOT NULL
                )%s""".formatted(d.identityPk(), d.tableSuffix()));
        out.add("""
                CREATE TABLE IF NOT EXISTS ledger_entries (
                  id %s,
                  order_id BIGINT NOT NULL,
                  account_id BIGINT NOT NULL,
                  direction CHAR(1) NOT NULL,
                  amount_minor BIGINT NOT NULL,
                  memo VARCHAR(64) NOT NULL,
                  posted_at %s NOT NULL
                )%s""".formatted(d.identityPk(), d.timestampType(), d.tableSuffix()));

        // Indexes separately: "CREATE INDEX IF NOT EXISTS" is PostgreSQL-only, and
        // MySQL before 8.0.29 has no equivalent — so these are attempted and their
        // "already exists" is tolerated by createIndexes() rather than guarded here.
        out.add("CREATE INDEX idx_orders_account ON orders (account_id, status)");
        out.add("CREATE INDEX idx_lines_order ON order_lines (order_id)");
        out.add("CREATE INDEX idx_entries_account ON ledger_entries (account_id, posted_at)");
        out.add("CREATE INDEX idx_entries_order ON ledger_entries (order_id)");
        return out;
    }

    public static void create(Connection c, Dialect d) throws SQLException {
        for (String stmt : ddl(d)) {
            try (Statement st = c.createStatement()) {
                st.execute(stmt);
            } catch (SQLException e) {
                if (stmt.startsWith("CREATE INDEX") && alreadyExists(e)) continue;
                throw e;
            }
        }
        log.info("schema ready ({})", d.engine.id);
    }

    private static boolean alreadyExists(SQLException e) {
        return e.getErrorCode() == 1061                 // MySQL ER_DUP_KEYNAME
                || "42P07".equals(e.getSQLState())      // PostgreSQL duplicate_table (indexes included)
                || "42000".equals(e.getSQLState());
    }
}
