package store

// The MySQL schema. Every statement is idempotent so EnsureSchema can run on
// every start, and the order matters only in that referenced tables come
// first. Ids are CHAR(26) — ULID-ish sortable strings generated by the app
// (see newID), not AUTO_INCREMENT, because MongoDB and Valkey need the same
// ids to be meaningful and an engine-assigned integer would not port.
//
// There are deliberately no foreign keys. A user deleting a security from the
// CRUD UI should succeed and leave its historical trades intact as an audit
// trail, which is the behaviour a FK would prevent; the same schema then works
// unchanged on the three non-relational backends.

// mysqlTables is the complete set of tables this app owns, and the list Wipe,
// DropSchema and Objects all iterate. Every table added to mysqlCreateStmts
// below must appear here too.
var mysqlTables = []string{
	"securities", "price_ticks", "portfolios", "orders", "trades", "holdings",
	"metrics", "sim_state", "agents", "events",
}

var mysqlCreateStmts = []string{
	`CREATE TABLE IF NOT EXISTS securities (
		id CHAR(26) NOT NULL PRIMARY KEY,
		symbol VARCHAR(16) NOT NULL,
		name VARCHAR(128) NOT NULL,
		sector VARCHAR(64) NOT NULL DEFAULT '',
		currency CHAR(3) NOT NULL DEFAULT 'USD',
		shares_outstanding BIGINT NOT NULL DEFAULT 0,
		open_price DECIMAL(18,4) NOT NULL DEFAULT 0,
		last_price DECIMAL(18,4) NOT NULL DEFAULT 0,
		day_high DECIMAL(18,4) NOT NULL DEFAULT 0,
		day_low DECIMAL(18,4) NOT NULL DEFAULT 0,
		day_volume BIGINT NOT NULL DEFAULT 0,
		listed TINYINT(1) NOT NULL DEFAULT 1,
		created_at DATETIME(3) NOT NULL,
		updated_at DATETIME(3) NOT NULL,
		UNIQUE KEY uq_securities_symbol (symbol),
		KEY ix_securities_sector (sector)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

	`CREATE TABLE IF NOT EXISTS price_ticks (
		id CHAR(26) NOT NULL PRIMARY KEY,
		security_id CHAR(26) NOT NULL,
		symbol VARCHAR(16) NOT NULL,
		ts DATETIME(3) NOT NULL,
		price DECIMAL(18,4) NOT NULL,
		volume BIGINT NOT NULL DEFAULT 0,
		KEY ix_ticks_security_ts (security_id, ts)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

	`CREATE TABLE IF NOT EXISTS portfolios (
		id CHAR(26) NOT NULL PRIMARY KEY,
		name VARCHAR(128) NOT NULL,
		owner VARCHAR(128) NOT NULL,
		cash DECIMAL(18,2) NOT NULL DEFAULT 0,
		created_at DATETIME(3) NOT NULL,
		updated_at DATETIME(3) NOT NULL,
		KEY ix_portfolios_owner (owner)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

	`CREATE TABLE IF NOT EXISTS orders (
		id CHAR(26) NOT NULL PRIMARY KEY,
		portfolio_id CHAR(26) NOT NULL,
		security_id CHAR(26) NOT NULL,
		symbol VARCHAR(16) NOT NULL,
		owner VARCHAR(128) NOT NULL DEFAULT '',
		side VARCHAR(8) NOT NULL,
		order_type VARCHAR(8) NOT NULL DEFAULT 'market',
		quantity BIGINT NOT NULL,
		limit_price DECIMAL(18,4) NOT NULL DEFAULT 0,
		status VARCHAR(16) NOT NULL DEFAULT 'open',
		created_at DATETIME(3) NOT NULL,
		filled_at DATETIME(3) NULL,
		KEY ix_orders_status_created (status, created_at),
		KEY ix_orders_portfolio (portfolio_id),
		KEY ix_orders_security (security_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

	`CREATE TABLE IF NOT EXISTS trades (
		id CHAR(26) NOT NULL PRIMARY KEY,
		order_id CHAR(26) NOT NULL,
		portfolio_id CHAR(26) NOT NULL,
		security_id CHAR(26) NOT NULL,
		symbol VARCHAR(16) NOT NULL,
		side VARCHAR(8) NOT NULL,
		quantity BIGINT NOT NULL,
		price DECIMAL(18,4) NOT NULL,
		ts DATETIME(3) NOT NULL,
		KEY ix_trades_ts (ts),
		KEY ix_trades_security (security_id),
		KEY ix_trades_portfolio (portfolio_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

	`CREATE TABLE IF NOT EXISTS holdings (
		portfolio_id CHAR(26) NOT NULL,
		security_id CHAR(26) NOT NULL,
		symbol VARCHAR(16) NOT NULL,
		quantity BIGINT NOT NULL DEFAULT 0,
		avg_cost DECIMAL(18,4) NOT NULL DEFAULT 0,
		updated_at DATETIME(3) NOT NULL,
		PRIMARY KEY (portfolio_id, security_id),
		KEY ix_holdings_security (security_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

	// The three tables every sibling sim carries: opaque JSON blobs upserted by
	// id, plus per-agent heartbeats.
	`CREATE TABLE IF NOT EXISTS metrics (
		id VARCHAR(16) NOT NULL PRIMARY KEY,
		payload JSON NOT NULL,
		updated_at DATETIME(3) NOT NULL
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

	`CREATE TABLE IF NOT EXISTS sim_state (
		id VARCHAR(16) NOT NULL PRIMARY KEY,
		payload JSON NOT NULL,
		updated_at DATETIME(3) NOT NULL
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

	`CREATE TABLE IF NOT EXISTS agents (
		agent_name VARCHAR(32) NOT NULL PRIMARY KEY,
		status VARCHAR(16) NOT NULL DEFAULT '',
		last_tick DATETIME(3) NOT NULL,
		detail VARCHAR(255) NOT NULL DEFAULT '',
		updated_at DATETIME(3) NOT NULL
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

	// The event feed. AUTO_INCREMENT here (and only here) because the feed is
	// read by a monotonic cursor, which a random id could not provide.
	`CREATE TABLE IF NOT EXISTS events (
		id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
		ts DATETIME(3) NOT NULL,
		kind VARCHAR(32) NOT NULL,
		symbol VARCHAR(16) NOT NULL DEFAULT '',
		message VARCHAR(512) NOT NULL
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
}
